apiVersion: apps/v1
kind: Deployment
metadata:
  name: gzip-project
  labels:
    app: gzip-project
    environment: dev
    group: demo
    project: gzip-demo
    tier: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gzip-project
  template:
    metadata:
      labels:
        app: gzip-project
        environment: dev
        group: demo
        project: gzip-demo
        tier: devops
    spec:
      containers:
      - name: project-gzip
        image: gole/project-gzip:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 10Mi
