apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io: /
  name: gzip-project
spec:
  rules:
  - host: gzip.golesuite.com
    http:
      paths:
      - backend:
          service:
            name: gzip-project
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - gzip.golesuite.com
    secretName: gzip-demo-golesuite-com
