apiVersion: apps/v1
kind: Deployment
metadata:
  name: gzip-project
  labels:
    app: gzip-project
    environment: dev
    group: demo
    project: gzip-demo
    tier: devops
    env: test
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: gzip-project
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gzip-project
        environment: dev
        group: demo
        project: gzip-demo
        tier: devops
        env: test
    spec:
      containers:
      - name: project-gzip
        image: gole/hello-world-java:tempo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VAULT
          valueFrom:
            secretKeyRef:
              name: secret-vault-test
              key: golesite
