resources:
  - deployment.yaml
  - service.yaml
#  - ingress.yaml
  
namespace: gzip 

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gole/project-gzip:latest
  newName: gole/project-gzip:latest
  newTag: latest
