resources:
- deployment.yaml
- service.yaml
#  - ingress.yaml
  
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gole/project-gzip
  newName: gole/project-gzip
  newTag: v0.1.5
