apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-gzip 
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:golesuite/project-gzip.git 
    targetRevision: HEAD
    path: k8s 
  destination:
    server: https://kubernetes.default.svc
    namespace: demo 
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

