name: Update PROD application image
on:
  push:
    tags:
      - '*'
env:
  GITHUB_TAG: ${{ github.REF_NAME }}

jobs:
  docker-build-push :
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gole/project-gzip:${{ env.GITHUB_TAG }}
