name: Update PROD application image
on:
  push:
    tags:
      - '*'
env:
  GITHUB_TAG: ${{ github.REF_NAME }}
  DOCKER_REGISTRY: gole
  IMAGE_NAME: project-gzip

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.REF_NAME }} . --no-cache
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.REF_NAME }}

  update-application:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - uses: actions/checkout@v3

      - name: Change image tag 
        run: |
          cd k8s/
          kustomize edit set image ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}=${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.REF_NAME }}
          cat kustomization.yaml

      - name: Commit changes
        run: |
          git config --local user.email "Maria Aline"
          git config --local user.name "aline@golesuite.com"
          git commit -a -m "Change image version using github tag value"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/argocd

